roles:
  - src: git+https://gitlab.com/devops1305151/docker-role.git
    version: main
    name: docker

roles:
  - src: git+https://gitlab.com/devops1305151/nginx-role.git
    version: main
    name: nginx   